######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 19 12:52:04 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tesqprocess.h
FORMS += tesqprocess.ui
SOURCES += main.cpp tesqprocess.cpp
