######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 15 14:50:28 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tesqprocess.h
FORMS += tesqprocess.ui
SOURCES += main.cpp tesqprocess.cpp
